defaultSeverity: warning
reportNeedlessDisables: true
reportInvalidScopeDisables: true
extends:
  - stylelint-config-standard-scss
  - stylelint-config-html/vue
rules:
  # `modern` not supported by Sass
  color-function-notation: legacy

  # always long to be consistent
  color-hex-length: long

  # allow Vue pseudo elements
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements: ["v-deep"]

  # allow grouping in Sass lists
  value-list-max-empty-lines: 1

  # prevent comments in generated CSS
  scss/comment-no-loud: true
