defaultSeverity: warning
reportNeedlessDisables: true
reportInvalidScopeDisables: true
extends:
  - stylelint-config-standard-scss
  - stylelint-config-html/vue
rules:
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements: ["v-deep"]
  scss/comment-no-loud: true
